#!/bin/bash

# Mongo Log Parser Installation Script for Mac/Linux
# This script installs log-parser to ~/.local/bin and sets up necessary configurations

set -e  # Exit on any error

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
INSTALL_DIR="$HOME/.local/bin"
SCRIPT_NAME="log-parser"
JAR_NAME="MongoLogParser.jar"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_color() {
    printf "${1}${2}${NC}\n"
}

print_color $BLUE "┌─────────────────────────────────────────────┐"
print_color $BLUE "│        Mongo Log Parser Installer          │"
print_color $BLUE "│     MongoDB Log Analysis & Reporting       │"
print_color $BLUE "└─────────────────────────────────────────────┘"
echo

# Check if Java is installed
print_color $BLUE "Checking Java installation..."
if ! command -v java &> /dev/null; then
    print_color $RED "Error: Java is not installed or not in PATH."
    print_color $YELLOW "Please install Java 8 or later and try again."
    print_color $YELLOW "  On macOS: brew install openjdk"
    print_color $YELLOW "  On Ubuntu: sudo apt install default-jdk"
    exit 1
fi

# Check Java version
JAVA_VERSION=$(java -version 2>&1 | head -n1 | cut -d'"' -f2 | cut -d'.' -f1)
# Handle version format for Java 8 and below (1.8, 1.7, etc)
if [[ $JAVA_VERSION == "1" ]]; then
    JAVA_VERSION=$(java -version 2>&1 | head -n1 | cut -d'"' -f2 | cut -d'.' -f2)
fi

if [[ $JAVA_VERSION -lt 8 ]]; then
    print_color $RED "Error: Java 8 or later is required. Found version: $JAVA_VERSION"
    exit 1
fi

print_color $GREEN "✓ Java version found"

# Build the project if JAR doesn't exist
if [ ! -f "$SCRIPT_DIR/bin/$JAR_NAME" ]; then
    print_color $YELLOW "JAR file not found. Building project..."
    cd "$SCRIPT_DIR"
    mvn clean package
    if [ ! -f "$SCRIPT_DIR/bin/$JAR_NAME" ]; then
        print_color $RED "Error: Build failed or JAR file not found at $SCRIPT_DIR/bin/$JAR_NAME"
        exit 1
    fi
fi

# Check if this is an update
if [ -f "$INSTALL_DIR/$SCRIPT_NAME" ]; then
    print_color $YELLOW "Existing installation found. Updating..."
else
    print_color $BLUE "Installing Mongo Log Parser..."
fi

# Create directories
mkdir -p "$INSTALL_DIR"

# Get absolute path to JAR (no copying - use directly from source)
JAR_ABS_PATH="$SCRIPT_DIR/bin/$JAR_NAME"

# Create wrapper script that points to the current directory's JAR
print_color $BLUE "Creating wrapper script with path: $JAR_ABS_PATH"
cat > "$INSTALL_DIR/$SCRIPT_NAME" << EOF
#!/bin/bash

# Mongo Log Parser wrapper script
# This script was generated by install.sh in $SCRIPT_DIR
JAR_FILE="$JAR_ABS_PATH"

if [[ ! -f "\$JAR_FILE" ]]; then
    echo "Error: Mongo Log Parser JAR file not found at \$JAR_FILE"
    echo "The JAR may have been moved or deleted."
    echo "Please run install.sh again from the mongo-log-parser directory."
    exit 1
fi

# Check if no arguments provided or just --help
if [ \$# -eq 0 ] || [ "\$1" = "--help" ] || [ "\$1" = "-h" ]; then
    # Run with --help to show usage
    cat << HELP
Mongo Log Parser - MongoDB Log Analysis & Reporting Tool

Usage: log-parser [options] <log-files...>

Options:
  -o, --output <file>       Output file name (default: report.html)
  -j, --json                Generate JSON output instead of HTML
  -r, --redact              Redact sensitive query information
  -s, --shard-tracking      Enable shard tracking (for sharded cluster logs)
  --ttl                     Include TTL operations analysis
  --filter <pattern>        Filter log entries by pattern
  --start <timestamp>       Start timestamp (e.g., 2025-01-01T00:00:00)
  --end <timestamp>         End timestamp
  --verbose                 Enable verbose output
  --help, -h                Show this help message

Examples:
  # Analyze a single log file
  log-parser mongod.log

  # Analyze multiple log files with HTML output
  log-parser mongod.log.* -o analysis.html

  # Generate JSON report with query redaction
  log-parser mongod.log -j -r -o report.json

  # Analyze sharded cluster logs with shard tracking
  log-parser shard*.log mongos.log -s -o cluster-report.html

  # Filter logs by time range
  log-parser mongod.log --start 2025-01-01T00:00:00 --end 2025-01-02T00:00:00

HELP
else
    # Pass all arguments to the JAR
    exec java -jar "\$JAR_FILE" "\$@"
fi
EOF

# Make script executable
chmod +x "$INSTALL_DIR/$SCRIPT_NAME"

print_color $GREEN "✓ Mongo Log Parser installed successfully!"
print_color $BLUE "Using JAR at: $JAR_ABS_PATH"
echo

# Check if the install directory is in PATH
if [[ ":$PATH:" == *":$INSTALL_DIR:"* ]]; then
    print_color $GREEN "✓ $INSTALL_DIR is already in your PATH"
    echo

    # Verify installation
    print_color $BLUE "Verifying installation..."
    if command -v log-parser &> /dev/null; then
        print_color $GREEN "✓ log-parser command is available"
        echo
    fi
else
    print_color $YELLOW "⚠️  $INSTALL_DIR is not in your PATH"
    echo
    print_color $BLUE "To add it to your PATH, add this line to your shell profile:"
    echo

    # Detect shell and provide appropriate instructions
    if [[ "$SHELL" == *"zsh"* ]]; then
        echo "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc"
        echo "    source ~/.zshrc"
    elif [[ "$SHELL" == *"bash"* ]]; then
        echo "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
        echo "    source ~/.bashrc"
    else
        echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
        echo "    # Add the above line to your shell's profile file"
    fi

    echo
    print_color $BLUE "Or run this command to add it now:"
    echo
    if [[ "$SHELL" == *"zsh"* ]]; then
        echo "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc && source ~/.zshrc"
    elif [[ "$SHELL" == *"bash"* ]]; then
        echo "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc && source ~/.bashrc"
    else
        echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
    fi
    echo
fi

print_color $GREEN "Installation complete!"
echo
print_color $BLUE "Usage:"
print_color $BLUE "  log-parser --help                         # Show usage and options"
print_color $BLUE "  log-parser mongod.log                     # Analyze a single log file"
print_color $BLUE "  log-parser *.log -o report.html           # Analyze multiple logs"
echo
print_color $BLUE "Examples:"
print_color $BLUE "  # Basic log analysis with HTML report"
print_color $BLUE "  log-parser mongod.log -o analysis.html"
echo
print_color $BLUE "  # Analyze with query redaction for security"
print_color $BLUE "  log-parser mongod.log -r -o secure-report.html"
echo
print_color $BLUE "  # Generate JSON output for programmatic processing"
print_color $BLUE "  log-parser mongod.log -j -o report.json"
echo
print_color $BLUE "  # Analyze sharded cluster logs with shard tracking"
print_color $BLUE "  log-parser shard*.log mongos.log -s -o cluster.html"
echo
print_color $GREEN "Mongo Log Parser is ready to use!"